### ISSUE TITLE
Change License from GPL to MIT?

### ISSUE THREAD

**Issue by Arlorean** [Corysia/Unity-Oculus-Example#2]
Hi Corysia, great work with the repository, it's really helpful. I noticed some of your other projects are MIT. Is there any chance of making this one MIT licensed? It's a great starting point as is but GPL will stop anyone making a game with this as the base code. Thanks.

**Comment by Arlorean** [comment]
I’m using 2019.2.4f1 but as soon as I switch from 1.38 to 1.40 my controllers/hands disappear on the Quest. Did you see the same thing?

**Comment by Scifibri** [comment]
Yes I need to look at that. I though maybe I’d messed up something. I’ve not had chance to check yet.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
